---
apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-svc
spec:
  ports:
  - port: 8082
  selector:
    app: kafka-rest
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-rest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: kafka-rest
        image: confluentinc/cp-kafka-rest:latest
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: kafka-zookeeper:2181
        - name: KAFKA_REST_HOST_NAME
          value: localhost
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082
        ports:
        - containerPort: 8082
